[project]
name = "evals"
version = "0.1.0"
description = ""
requires-python = ">=3.10, <3.13"
dependencies = [
    "agentuity>=0.0.85",
    "aiohttp>=3.11.18",
    "anthropic>=0.52.0",
    "requests>=2.31.0",
]
